-- CreateTable
CREATE TABLE "files" (
    "userid" STRING NOT NULL,
    "file_id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "file_name" STRING NOT NULL,
    "file_description" STRING NOT NULL,
    "cid" STRING NOT NULL,

    CONSTRAINT "files_pkey" PRIMARY KEY ("file_id")
);
